### ISSUE TITLE
可以加上simple-obfs 吗？

### ISSUE THREAD

**Issue by zhouad** [imMMX/ubnt-mips-shadowsocks-libev#4]
你好，前几天刚刚入手ER-X SFP，正在折腾编译的问题，机缘看到你的这个项目，非常的方便，特别感谢！就是我们的服务器是用了obfs的，所以有没有可能请您加上编译simple-obfs功能？感谢！

**Comment by zhouad** [comment]
参考你的脚本加了一下，测试可以使用了！😄
echo -e "$green Installing simple-obfs...$end"
cd
git clone https://github.com/shadowsocks/simple-obfs
cd simple-obfs
git submodule init && git submodule update
./autogen.sh
LIBS="-lpthread -lm" \
LDFLAGS="-Wl,-static -static -static-libgcc \
-L$prefix_path/libsodium/lib \
-L$prefix_path/libev/lib \
-L$prefix_path/libcares/lib" \
CFLAGS="-I$prefix_path/libsodium/include \
-I$prefix_path/libev/include \
-I$prefix_path/libcares/include" \
./configure --host=$host  --prefix=$prefix_path/ss-bin \
--disable-ssp \
--disable-documentation \
&& make \
&& make install

**Comment by imMMX** [comment]
可以提个 PR 过来😊

**Comment by imMMX** [comment]
Merged.

**Comment by NubiaYin** [comment]
你好，可否编译个ssr的版本呢？
