### ISSUE TITLE
Couldn't find libev

### ISSUE THREAD

**Issue by yingqiangyu** [imMMX/ubnt-mips-shadowsocks-libev#9]
[issue.log](https://github.com/imMMX/ubnt-mips-shadowsocks-libev/files/2874016/issue.log)
Please review this log file.
Error message at the end of log file.

**Comment by imMMX** [comment]
```
Installing libev...
--2019-02-18 03:29:17--  http://dist.schmorp.de/libev/libev-4.25.tar.gz
Resolving dist.schmorp.de (dist.schmorp.de)... 5.9.56.12
Connecting to dist.schmorp.de (dist.schmorp.de)|5.9.56.12|:80... failed: Connection refused.
```
seems blocked by the GFW. u can try this one. [voidlinux](https://sources.voidlinux.org/libev-4.25/libev-4.25.tar.gz)
